// src/components/Admin/AdminEditor.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import { ChevronDown, ChevronLeft } from 'lucide-vue-next';
import EditorJsField from './EditorJsField.vue';
import { flushEditorContent } from './EditorJsField.vue';
import type { OutputData } from '@editorjs/editorjs';
import { parseStoredContentToEditorJs } from '../../lib/editorjs-content.ts';
import { getTranslation } from '@/i18n/i18n.ts';
import { resolveImageUrl } from '../../lib/images.ts';

type Translation = {
  lang: string;
  title: string;
  content: string;
  published: boolean;
};

export type AdminPostDraft = {
  id: string;
  slug: string;
  type: string;
  author: string;
  image: string;
  translations: Translation[];
};

const props = defineProps<{
  post: AdminPostDraft;
  onClose: () => void;
  onSaved: () => void;
}>();

const LANGS = ['en', 'es', 'fr'] as const;
type Lang = (typeof LANGS)[number];

const draft = ref<AdminPostDraft>(structuredClone(props.post) as AdminPostDraft);
const activeLang = ref<string>('en');
const saving = ref(false);
const saveError = ref('');

const contentSaveRef = ref<(() => Promise<OutputData>) | null>(null);
const descriptionSaveRefs = ref<Record<string, (() => Promise<OutputData>) | null>>({
  en: null,
  es: null,
  fr: null,
});

type ProjectMeta = {
  category: string;
  status: string;
  description: string;
  link: string;
};

const projectMeta = ref<ProjectMeta>({
  category: 'Desktop Game',
  status: 'In Development',
  description: '',
  link: '',
});

const activeTranslation = computed(() => {
  const d = draft.value;
  const lang = activeLang.value;
  return (
    d.translations.find((t) => t.lang === lang) ?? {
      lang,
      title: '',
      content: '{"blocks":[]}',
      published: false,
    }
  );
});

function parseProjectContent(content: string): ProjectMeta {
  try {
    const parsed = JSON.parse(content || '{}');
    return {
      category: parsed.category || 'Desktop Game',
      status: parsed.status || 'In Development',
      description: parsed.description || '',
      link: parsed.link || '',
    };
  } catch {
    return {
      category: 'Desktop Game',
      status: 'In Development',
      description: '',
      link: '',
    };
  }
}

watch(activeLang, (newLang) => {
  if (draft.value.type === 'project') {
    const t = activeTranslation.value;
    const parsed = parseProjectContent(t.content);
    projectMeta.value = parsed;
  }
}, { immediate: true });

const contentInitial = computed(() => activeTranslation.value.content || '{"blocks":[]}');
const descriptionInitial = computed(() => projectMeta.value.description);

function handleClose() {
  props.onClose();
}

function switchLang(lang: string) {
  activeLang.value = lang;
}

async function handleSaveClick() {
  saving.value = true;
  saveError.value = '';

  try {
    const d = draft.value;
    const lang = activeLang.value;
    let flushedDescription = projectMeta.value.description;
    let flushedContent: string | undefined;

    if (d.type === 'project') {
      const descJson = await flushEditorContent(descriptionSaveRefs.value[lang]);
      if (descJson !== undefined) {
        flushedDescription = descJson;
        projectMeta.value = { ...projectMeta.value, description: descJson };
      }
    } else {
      flushedContent = await flushEditorContent(contentSaveRef.value);
      if (flushedContent !== undefined) {
        const idx = d.translations.findIndex((t) => t.lang === lang);
        if (idx >= 0) {
          d.translations[idx] = { ...d.translations[idx], content: flushedContent! };
        }
      }
    }

    const form = document.getElementById('admin-editor-form') as HTMLFormElement | null;
    const fd = form ? new FormData(form) : null;

    const finalSlug = (fd?.get('slug') as string) || d.slug;
    const finalAuthor = (fd?.get('author') as string) || d.author;
    const finalImage = (fd?.get('image') as string) || '';
    const postType = (fd?.get('post-type') as string) || d.type;

    const translationPayload = LANGS.map((l) => {
      const existing = d.translations.find((t) => t.lang === l);
      if (l === activeLang.value) {
        let content = l === activeLang.value ? (flushedContent ?? existing?.content) : (existing?.content);
        if (postType === 'project') {
          const meta: ProjectMeta = {
            category: (fd?.get(`project-category-${l}`) as string) || projectMeta.value.category,
            status: (fd?.get(`project-status-${l}`) as string) || projectMeta.value.status,
            description: flushedDescription,
            link: (fd?.get(`project-link-${l}`) as string) || projectMeta.value.link,
          };
          if (l === activeLang.value) {
            meta.description = flushedDescription;
          }
          content = JSON.stringify(meta);
        }
        const titleField = fd?.get('post-title');
        return {
          lang: l,
          title: (titleField as string) || existing?.title || '',
          content,
          published: existing?.published ?? false,
        };
      }
      return (
        existing || {
          lang: l,
          title: '',
          content: '{"blocks":[]}',
          published: false,
        }
      );
    });

    const payload = {
      ...(d.id !== 'new' ? { id: d.id } : {}),
      slug: finalSlug,
      type: postType,
      author: finalAuthor,
      image: finalImage,
      translations: translationPayload,
    };

    const endpoint = d.id === 'new' ? '/api/admin/posts' : `/api/admin/posts/${encodeURIComponent(d.id)}`;
    const method = d.id === 'new' ? 'POST' : 'PUT';

    const res = await fetch(endpoint, {
      method,
      credentials: 'include',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    });

    if (!res.ok) {
      const errBody = (await res.json().catch(() => ({}))) as { error?: string };
      saveError.value = errBody.error || `Save failed (${res.status})`;
      return;
    }

    props.onSaved();
  } catch (e) {
    saveError.value = e instanceof Error ? e.message : 'Network error while saving';
  } finally {
    saving.value = false;
  }
}
</script>

<template>
  <div class="fixed inset-0 z-50 bg-neutral-950/90 backdrop-blur-md flex items-center justify-center md:p-4">
    <div class="bg-neutral-900 border border-neutral-800 md:rounded-2xl w-full md:max-w-5xl h-full md:h-[90vh] flex flex-col shadow-2xl overflow-hidden">
      <form
        id="admin-editor-form"
        class="flex flex-col h-full"
        method="POST"
      >
        <div class="px-4 py-3 md:px-6 md:py-4 border-b border-neutral-800 flex flex-col md:flex-row md:justify-between md:items-center bg-neutral-900 gap-4">
          <div class="flex items-center gap-2 w-full md:max-w-3xl">
            <button
              type="button"
              @click="handleClose"
              class="md:hidden p-2 -ml-2 text-neutral-400 hover:text-white transition-colors"
              aria-label="Back"
            >
              <ChevronLeft class="w-6 h-6" />
            </button>
            <div class="grid grid-cols-2 md:flex md:gap-4 items-center flex-1 gap-3">
              <input
                type="text"
                name="slug"
                :value="draft.slug"
                :placeholder="getTranslation('admin.editor.slug')"
                class="bg-neutral-800 border border-neutral-700 text-xs md:text-sm rounded-lg px-3 py-2 text-white focus:outline-none focus:ring-1 focus:ring-orange-500 w-full md:w-1/4"
              />
              <input
                type="text"
                name="author"
                :value="draft.author"
                :placeholder="getTranslation('admin.editor.author')"
                class="bg-neutral-800 border border-neutral-700 text-xs md:text-sm rounded-lg px-3 py-2 text-white focus:outline-none focus:ring-1 focus:ring-orange-500 w-full md:w-1/4"
              />
              <div class="col-span-2 md:flex-1 flex gap-2 items-center">
                <input
                  type="text"
                  name="image"
                  :value="draft.image"
                  :placeholder="getTranslation('admin.editor.image')"
                  list="public-images"
                  class="bg-neutral-800 border border-neutral-700 text-xs md:text-sm rounded-lg px-3 py-2 text-white focus:outline-none focus:ring-1 focus:ring-orange-500 w-full"
                />
                <datalist id="public-images">
                  <optgroup label="Blog Images">
                    <option value="/blog/astro-islands.jpg" />
                    <option value="/blog/exact-slice-accuracy.jpg" />
                    <option value="/blog/gaming-future.jpg" />
                    <option value="/blog/inverse-pulse-creation.jpg" />
                    <option value="/blog/micro-interactions-godot.jpg" />
                    <option value="/blog/studio-founding.jpg" />
                  </optgroup>
                  <optgroup label="Project Images">
                    <option value="/projects/photo-1504384308090-c894fdcc538d.avif" />
                    <option value="/projects/photo-1512941937669-90a1b58e7e9c.avif" />
                    <option value="/projects/photo-1542751371-adc38448a05e.avif" />
                    <option value="/projects/photo-1550745165-9bc0b252726f.avif" />
                  </optgroup>
                </datalist>
                <div class="w-8 h-8 rounded bg-neutral-800 overflow-hidden border border-neutral-700 shrink-0">
                  <img
                    v-if="draft.image"
                    :src="resolveImageUrl(draft.image)"
                    alt=""
                    class="w-full h-full object-cover"
                  />
                </div>
              </div>
              <div class="col-span-2 md:col-span-1 relative">
                <select
                  name="post-type"
                  :value="draft.type"
                  class="bg-neutral-800 border border-neutral-700 text-xs md:text-sm rounded-lg px-3 py-2 focus:outline-none text-white appearance-none w-full md:min-w-[100px]"
                >
                  <option value="blog">{{ getTranslation('admin.dashboard.blogPosts') }}</option>
                  <option value="project">{{ getTranslation('admin.dashboard.portfolio') }}</option>
                  <option value="case_study">{{ getTranslation('admin.dashboard.caseStudies') }}</option>
                </select>
                <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-neutral-500">
                  <ChevronDown class="h-4 w-4" />
                </div>
              </div>
            </div>
          </div>
          <div class="flex gap-3 justify-end border-t border-neutral-800 md:border-none pt-3 md:pt-0">
            <p v-if="saveError" class="text-red-400 text-xs self-center max-w-[200px] md:max-w-md text-right">
              {{ saveError }}
            </p>
            <button
              type="button"
              @click="handleClose"
              class="px-4 py-2 text-xs md:text-sm text-neutral-400 hover:text-white transition-colors"
            >
              {{ getTranslation('admin.editor.cancel') }}
            </button>
            <button
              type="button"
              :disabled="saving"
              @click="handleSaveClick"
              class="bg-orange-500 hover:bg-orange-600 text-white px-4 py-2 rounded-lg text-xs md:text-sm font-medium shadow-lg disabled:opacity-50 transition-all"
            >
              {{ saving ? getTranslation('admin.editor.saving') : getTranslation('admin.editor.savePost') }}
            </button>
          </div>
        </div>

        <div class="flex border-b border-neutral-800 bg-neutral-900/50 px-4 md:px-6 pt-1 md:pt-2 gap-1 md:gap-2 overflow-x-auto no-scrollbar">
          <button
            v-for="lang in LANGS"
            :key="lang"
            type="button"
            @click="switchLang(lang)"
            class="px-4 py-2.5 md:py-3 text-xs md:text-sm font-medium border-b-2 transition-colors shrink-0"
            :class="activeLang === lang
              ? 'border-orange-500 text-orange-400'
              : 'border-transparent text-neutral-500 hover:text-neutral-300'"
          >
            {{ lang.toUpperCase() }}
          </button>
        </div>

        <div class="flex-1 overflow-y-auto p-4 md:p-8 relative bg-neutral-950 custom-scrollbar">
          <div class="max-w-3xl mx-auto">
            <input
              type="text"
              name="post-title"
              :value="activeTranslation.title"
              :placeholder="getTranslation('admin.editor.postTitle')"
              class="w-full bg-transparent text-2xl md:text-4xl font-bold text-white border-none focus:outline-none mb-6 md:mb-8 placeholder-neutral-800"
            />

            <div v-if="draft.type === 'project'" class="space-y-4 md:space-y-6">
              <div>
                <label class="block text-sm font-medium text-neutral-400 mb-2">
                  {{ getTranslation('admin.editor.category') }}
                </label>
                <select
                  name="project-category-en"
                  v-model="projectMeta.category"
                  class="bg-neutral-800 border border-neutral-700 text-sm rounded-lg px-4 py-3 text-white focus:outline-none focus:ring-1 focus:ring-orange-500 w-full"
                >
                  <option value="Desktop Game">{{ getTranslation('admin.editor.projectCategory.desktop') }}</option>
                  <option value="Mobile Game">{{ getTranslation('admin.editor.projectCategory.mobileGame') }}</option>
                  <option value="Mobile App">{{ getTranslation('admin.editor.projectCategory.mobileApp') }}</option>
                  <option value="Web Application">{{ getTranslation('admin.editor.projectCategory.webApp') }}</option>
                </select>
              </div>
              <div>
                <label class="block text-sm font-medium text-neutral-400 mb-2">
                  {{ getTranslation('admin.editor.status') }}
                </label>
                <select
                  name="project-status-en"
                  v-model="projectMeta.status"
                  class="bg-neutral-800 border border-neutral-700 text-sm rounded-lg px-4 py-3 text-white focus:outline-none focus:ring-1 focus:ring-orange-500 w-full"
                >
                  <option value="Available Now">{{ getTranslation('admin.editor.projectStatus.now') }}</option>
                  <option value="Coming Soon">{{ getTranslation('admin.editor.projectStatus.soon') }}</option>
                  <option value="Publishing">{{ getTranslation('admin.editor.projectStatus.publishing') }}</option>
                  <option value="In Development">{{ getTranslation('admin.editor.projectStatus.dev') }}</option>
                </select>
              </div>
              <div>
                <label class="block text-sm font-medium text-neutral-400 mb-2">
                  {{ getTranslation('admin.editor.shortDescription') }}
                </label>
                <EditorJsField
                  :root-id="`project-description-${activeLang}`"
                  :lang-key="`project-description-${activeLang}`"
                  :initial-content="descriptionInitial"
                  :minimal="true"
                  :on-content-change="(json) => { projectMeta.description = json; }"
                  :register-save="(fn) => { descriptionSaveRefs[activeLang] = fn; }"
                />
              </div>
              <div>
                <label class="block text-sm font-medium text-neutral-400 mb-2">
                  {{ getTranslation('admin.editor.externalLink') }}
                </label>
                <input
                  type="url"
                  name="project-link-en"
                  v-model="projectMeta.link"
                  placeholder="https://store.steampowered.com/app/..."
                  class="bg-neutral-800 border border-neutral-700 text-sm rounded-lg px-4 py-3 text-white focus:outline-none focus:ring-1 focus:ring-orange-500 w-full"
                />
              </div>
            </div>
            <EditorJsField
              v-else
              :root-id="`content-${activeLang}`"
              :lang-key="`${activeLang}-${draft.type}`"
              :initial-content="contentInitial"
              :on-content-change="(json) => {
                const idx = draft.translations.findIndex((t) => t.lang === activeLang);
                if (idx >= 0) {
                  draft.translations[idx] = { ...draft.translations[idx], content: json };
                }
              }"
              :register-save="(fn) => { contentSaveRef = fn; }"
            />
          </div>
        </div>
      </form>
    </div>
  </div>
</template>

// src/components/Admin/AdminEditor.tsx
import { createEffect, createSignal, untrack } from "@emberkit/core";
import { getTranslation } from "../../i18n/i18n.ts";
import { resolveImageUrl } from "../../lib/images.ts";
import {
  EditorJsField,
  flushEditorContent,
} from "./EditorJsField.tsx";
import type { OutputData } from "@editorjs/editorjs";
import { IconChevronDown, IconChevronLeft } from "@emberkit/icons";

type Translation = {
  lang: string;
  title: string;
  content: string;
  published: boolean;
};

export type AdminPostDraft = {
  id: string;
  slug: string;
  type: string;
  author: string;
  image: string;
  translations: Translation[];
};

let editorUid = 0;
function nextEditorHolderId() {
  editorUid += 1;
  return `editorjs-field-${editorUid}`;
}

const LANGS = ["en", "es", "fr"] as const;

export default function AdminEditor(props: {
  post: AdminPostDraft;
  onClose: () => void;
  onSaved: () => void;
}) {
  const [draft, setDraft] = createSignal<AdminPostDraft>(
    structuredClone(props.post) as AdminPostDraft,
  );
  const [activeLang, setActiveLang] = createSignal<string>("en");
  const [saving, setSaving] = createSignal(false);
  const [saveError, setSaveError] = createSignal("");
  
  const contentSaveRef: { current: (() => Promise<OutputData>) | null } = {
    current: null,
  };
  const descriptionSaveRefs: {
    current: Record<string, (() => Promise<OutputData>) | null>;
  } = {
    current: { en: null, es: null, fr: null },
  };

  const contentRootId = nextEditorHolderId();
  const descriptionRootIds: Record<string, string> = {
    en: nextEditorHolderId(),
    es: nextEditorHolderId(),
    fr: nextEditorHolderId(),
  };

  type ProjectMeta = {
    category: string;
    status: string;
    description: string;
    link: string;
  };

  const [projectMeta, setProjectMeta] = createSignal<ProjectMeta>({
    category: "Desktop Game",
    status: "In Development",
    description: "",
    link: "",
  });

  const activeTranslation = () => {
    const d = draft();
    const lang = activeLang();
    return (
      d.translations.find((t) => t.lang === lang) ?? {
        lang,
        title: "",
        content: '{"blocks":[]}',
        published: false,
      }
    );
  };

  const loadProjectMeta = () => {
    if (draft().type !== "project") return;
    const t = activeTranslation();
    try {
      const parsed = JSON.parse(t.content || "{}");
      // If description looks like JSON, extract just the description field
      let description = parsed.description || "";
      if (typeof description === "object") {
        description = "";
      }
      setProjectMeta({
        category: parsed.category || "Desktop Game",
        status: parsed.status || "In Development",
        description,
        link: parsed.link || "",
      });
    } catch {
      setProjectMeta({
        category: "Desktop Game",
        status: "In Development",
        description: "",
        link: "",
      });
    }
  };

  createEffect(() => {
    activeLang();
    if (draft().type !== "project") return;
    untrack(loadProjectMeta);
  });

  const updateTranslation = (
    lang: string,
    patch: Partial<Translation>,
  ) => {
    setDraft((d) => ({
      ...d,
      translations: d.translations.map((tr) =>
        tr.lang === lang ? { ...tr, ...patch } : tr,
      ),
    }));
  };

  const handleClose = () => props.onClose();

  const switchLang = (lang: string) => {
    setActiveLang(lang);
  };

  const handleSubmit = async (e: Event) => {
    e.preventDefault();
    setSaving(true);
    setSaveError("");

    try {
      const form = e.target as HTMLFormElement;
      const fd = new FormData(form);

      const d = draft();

      const lang = activeLang();
      let flushedDescription = projectMeta().description;
      let flushedContent: string | undefined;
      if (d.type === "project") {
        const descJson = await flushEditorContent(
          descriptionSaveRefs.current[lang],
        );
        if (descJson !== undefined) {
          flushedDescription = descJson;
          setProjectMeta((m) => ({ ...m, description: descJson }));
        }
      } else {
        flushedContent = await flushEditorContent(contentSaveRef.current);
        if (flushedContent !== undefined) {
          updateTranslation(lang, { content: flushedContent });
        }
      }

      // Build payload from form data
      const postType = (fd.get("post-type") as string) || d.type;
      const payload: AdminPostDraft = {
        id: d.id,
        slug: fd.get("slug") as string || d.slug,
        author: fd.get("author") as string || d.author,
        image: fd.get("image") as string || "",
        type: postType,
        translations: LANGS.map((lang) => {
          const existing = d.translations.find((t) => t.lang === lang);
          if (lang === activeLang()) {
            // Active language: read from form
            let content =
              flushedContent ?? existing?.content ?? '{"blocks":[]}';
            if (postType === "project") {
              const meta: ProjectMeta = {
                category:
                  (fd.get(`project-category-${lang}`) as string) ||
                  "Desktop Game",
                status:
                  (fd.get(`project-status-${lang}`) as string) ||
                  "In Development",
                description: flushedDescription,
                link: (fd.get(`project-link-${lang}`) as string) || "",
              };
              content = JSON.stringify(meta);
            } else {
              // For blog/case_study, content was flushed from Editor.js above
              const titleField = fd.get("post-title");
              if (titleField) {
                return {
                  lang,
                  title: titleField as string,
                  content,
                  published: existing?.published ?? false,
                };
              }
            }
            return {
              lang,
              title: fd.get("post-title") as string || existing?.title || "",
              content,
              published: existing?.published ?? false,
            };
          }
          // Inactive language: preserve existing
          return (
            existing || {
              lang,
              title: "",
              content: '{"blocks":[]}',
              published: false,
            }
          );
        }),
      };

      const endpoint =
        d.id === "new" ? "/api/admin/posts" : `/api/admin/posts/${encodeURIComponent(d.id)}`;
      const method = d.id === "new" ? "POST" : "PUT";

      const res = await fetch(endpoint, {
        method,
        credentials: "include",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });

      if (!res.ok) {
        const errBody = (await res.json().catch(() => ({}))) as {
          error?: string;
        };
        setSaveError(errBody.error || `Save failed (${res.status})`);
        return;
      }

      props.onSaved();
    } catch (e) {
      setSaveError(
        e instanceof Error ? e.message : "Network error while saving",
      );
    } finally {
      setSaving(false);
    }
  };

  // No form listener needed — use onClick on submit button instead
  const handleSaveClick = async () => {
    // Manually construct a FormData-like object from the form
    const form = document.getElementById("admin-editor-form") as HTMLFormElement;
    if (!form) {
      setSaveError("Form not found");
      return;
    }
    
    const event = new Event("submit", { bubbles: true, cancelable: true });
    const prevented = !form.dispatchEvent(event);
    if (prevented) return;
    
    await handleSubmit(event);
  };

  const tr = activeTranslation();
  const contentInitial = tr.content || '{"blocks":[]}';
  const descriptionInitial = projectMeta().description;

  return (
    <div className="fixed inset-0 z-50 bg-neutral-950/90 backdrop-blur-md flex items-center justify-center md:p-4">
      <div className="bg-neutral-900 border border-neutral-800 md:rounded-2xl w-full md:max-w-5xl h-full md:h-[90vh] flex flex-col shadow-2xl overflow-hidden">
        <form
          id="admin-editor-form"
          className="flex flex-col h-full"
          method="POST"
        >
          <div className="px-4 py-3 md:px-6 md:py-4 border-b border-neutral-800 flex flex-col md:flex-row md:justify-between md:items-center bg-neutral-900 gap-4">
            <div className="flex items-center gap-2 w-full md:max-w-3xl">
              <button
                type="button"
                onClick={handleClose}
                className="md:hidden p-2 -ml-2 text-neutral-400 hover:text-white transition-colors"
                aria-label="Back"
              >
                <IconChevronLeft className="w-6 h-6" />
              </button>
              <div className="grid grid-cols-2 md:flex md:gap-4 items-center flex-1 gap-3">
                <input
                  type="text"
                  name="slug"
                  defaultValue={draft().slug}
                  placeholder={getTranslation("admin.editor.slug")}
                  className="bg-neutral-800 border border-neutral-700 text-xs md:text-sm rounded-lg px-3 py-2 text-white focus:outline-none focus:ring-1 focus:ring-orange-500 w-full md:w-1/4"
                />
                <input
                  type="text"
                  name="author"
                  defaultValue={draft().author}
                  placeholder={getTranslation("admin.editor.author")}
                  className="bg-neutral-800 border border-neutral-700 text-xs md:text-sm rounded-lg px-3 py-2 text-white focus:outline-none focus:ring-1 focus:ring-orange-500 w-full md:w-1/4"
                />
                <div className="col-span-2 md:flex-1 flex gap-2 items-center">
                  <input
                    type="text"
                    name="image"
                    defaultValue={draft().image}
                    placeholder={getTranslation("admin.editor.image")}
                    list="public-images"
                    className="bg-neutral-800 border border-neutral-700 text-xs md:text-sm rounded-lg px-3 py-2 text-white focus:outline-none focus:ring-1 focus:ring-orange-500 w-full"
                  />
                  <datalist id="public-images">
                    <optgroup label="Blog Images">
                      <option value="/blog/astro-islands.jpg" />
                      <option value="/blog/exact-slice-accuracy.jpg" />
                      <option value="/blog/gaming-future.jpg" />
                      <option value="/blog/inverse-pulse-creation.jpg" />
                      <option value="/blog/micro-interactions-godot.jpg" />
                      <option value="/blog/studio-founding.jpg" />
                    </optgroup>
                    <optgroup label="Project Images">
                      <option value="/projects/photo-1504384308090-c894fdcc538d.avif" />
                      <option value="/projects/photo-1512941937669-90a1b58e7e9c.avif" />
                      <option value="/projects/photo-1542751371-adc38448a05e.avif" />
                      <option value="/projects/photo-1550745165-9bc0b252726f.avif" />
                    </optgroup>
                  </datalist>
                  {draft().image ? (
                    <div className="w-8 h-8 rounded bg-neutral-800 overflow-hidden border border-neutral-700 shrink-0">
                      <img
                        src={resolveImageUrl(draft().image)}
                        alt=""
                        className="w-full h-full object-cover"
                      />
                    </div>
                  ) : null}
                </div>
                <div className="col-span-2 md:col-span-1 relative">
                  <select
                    name="post-type"
                    defaultValue={draft().type}
                    className="bg-neutral-800 border border-neutral-700 text-xs md:text-sm rounded-lg px-3 py-2 focus:outline-none text-white appearance-none w-full md:min-w-[100px]"
                  >
                    <option value="blog">
                      {getTranslation("admin.dashboard.blogPosts")}
                    </option>
                    <option value="project">
                      {getTranslation("admin.dashboard.portfolio")}
                    </option>
                    <option value="case_study">
                      {getTranslation("admin.dashboard.caseStudies")}
                    </option>
                  </select>
                  <div className="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-neutral-500">
                    <IconChevronDown className="h-4 w-4" />
                  </div>
                </div>
              </div>
            </div>
            <div className="flex gap-3 justify-end border-t border-neutral-800 md:border-none pt-3 md:pt-0">
              {saveError() ? (
                <p className="text-red-400 text-xs self-center max-w-[200px] md:max-w-md text-right">
                  {saveError()}
                </p>
              ) : null}
              <button
                type="button"
                onClick={handleClose}
                className="px-4 py-2 text-xs md:text-sm text-neutral-400 hover:text-white transition-colors"
              >
                {getTranslation("admin.editor.cancel")}
              </button>
              <button
                type="button"
                onClick={handleSaveClick}
                disabled={saving()}
                className="bg-orange-500 hover:bg-orange-600 text-white px-4 py-2 rounded-lg text-xs md:text-sm font-medium shadow-lg disabled:opacity-50 transition-all"
              >
                {saving()
                  ? getTranslation("admin.editor.saving")
                  : getTranslation("admin.editor.savePost")}
              </button>
            </div>
          </div>

          <div className="flex border-b border-neutral-800 bg-neutral-900/50 px-4 md:px-6 pt-1 md:pt-2 gap-1 md:gap-2 overflow-x-auto no-scrollbar">
            {LANGS.map((lang) => (
              <button
                key={lang}
                type="button"
                onClick={() => switchLang(lang)}
                className={
                  activeLang() === lang
                    ? "px-4 py-2.5 md:py-3 text-xs md:text-sm font-medium border-b-2 transition-colors shrink-0 border-orange-500 text-orange-400"
                    : "px-4 py-2.5 md:py-3 text-xs md:text-sm font-medium border-b-2 transition-colors shrink-0 border-transparent text-neutral-500 hover:text-neutral-300"
                }
              >
                {lang.toUpperCase()}
              </button>
            ))}
          </div>

          <div className="flex-1 overflow-y-auto p-4 md:p-8 relative bg-neutral-950 custom-scrollbar">
            <div className="max-w-3xl mx-auto">
              <input
                type="text"
                name="post-title"
                defaultValue={tr.title}
                placeholder={getTranslation("admin.editor.postTitle")}
                className="w-full bg-transparent text-2xl md:text-4xl font-bold text-white border-none focus:outline-none mb-6 md:mb-8 placeholder-neutral-800"
              />

              {draft().type === "project" ? (
                <div className="space-y-4 md:space-y-6">
                  <div>
                    <label className="block text-sm font-medium text-neutral-400 mb-2">
                      {getTranslation("admin.editor.category")}
                    </label>
                    <select
                      name={`project-category-${activeLang()}`}
                      defaultValue={projectMeta().category}
                      className="bg-neutral-800 border border-neutral-700 text-sm rounded-lg px-4 py-3 text-white focus:outline-none focus:ring-1 focus:ring-orange-500 w-full"
                    >
                      <option value="Desktop Game">
                        {getTranslation("admin.editor.projectCategory.desktop")}
                      </option>
                      <option value="Mobile Game">
                        {getTranslation("admin.editor.projectCategory.mobileGame")}
                      </option>
                      <option value="Mobile App">
                        {getTranslation("admin.editor.projectCategory.mobileApp")}
                      </option>
                      <option value="Web Application">
                        {getTranslation("admin.editor.projectCategory.webApp")}
                      </option>
                    </select>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-neutral-400 mb-2">
                      {getTranslation("admin.editor.status")}
                    </label>
                    <select
                      name={`project-status-${activeLang()}`}
                      defaultValue={projectMeta().status}
                      className="bg-neutral-800 border border-neutral-700 text-sm rounded-lg px-4 py-3 text-white focus:outline-none focus:ring-1 focus:ring-orange-500 w-full"
                    >
                      <option value="Available Now">
                        {getTranslation("admin.editor.projectStatus.now")}
                      </option>
                      <option value="Coming Soon">
                        {getTranslation("admin.editor.projectStatus.soon")}
                      </option>
                      <option value="Publishing">
                        {getTranslation("admin.editor.projectStatus.publishing")}
                      </option>
                      <option value="In Development">
                        {getTranslation("admin.editor.projectStatus.dev")}
                      </option>
                    </select>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-neutral-400 mb-2">
                      {getTranslation("admin.editor.shortDescription")}
                    </label>
                    <EditorJsField
                      rootId={descriptionRootIds[activeLang()]}
                      langKey={`project-description-${activeLang()}`}
                      initialContent={descriptionInitial}
                      minimal
                      onContentChange={(json) => {
                        setProjectMeta((m) => ({ ...m, description: json }));
                      }}
                      registerSave={(fn) => {
                        descriptionSaveRefs.current[activeLang()] = fn;
                      }}
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-neutral-400 mb-2">
                      {getTranslation("admin.editor.externalLink")}
                    </label>
                    <input
                      type="url"
                      name={`project-link-${activeLang()}`}
                      defaultValue={projectMeta().link}
                      placeholder="https://store.steampowered.com/app/..."
                      className="bg-neutral-800 border border-neutral-700 text-sm rounded-lg px-4 py-3 text-white focus:outline-none focus:ring-1 focus:ring-orange-500 w-full"
                    />
                  </div>
                </div>
              ) : (
                <EditorJsField
                  rootId={contentRootId}
                  langKey={`${activeLang()}-${draft().type}`}
                  initialContent={contentInitial}
                  onContentChange={(json) =>
                    updateTranslation(activeLang(), { content: json })
                  }
                  registerSave={(fn) => {
                    contentSaveRef.current = fn;
                  }}
                />
              )}
            </div>
          </div>
        </form>
      </div>
    </div>
  );
}
